#!/usr/bin/env python

import os
import sys
import subprocess
import fnmatch
import re
import inspect

wo_path = os.path.abspath(os.path.split(inspect.getfile(
    inspect.currentframe()))[0])

if wo_path not in sys.path:
    sys.path.insert(0, wo_path)

my_env=os.environ.copy()
my_env["NCL_LIB"] = os.path.join(my_env["HOME"], 'nsc/ncl-lib/')
my_env["WRFOUT"] = wo_path
dir_file = "run_dirs"
wrf_dom = "3"


def set_ncl_fin(env):
    # reg= fnmatch.translate('wrfout*3')
    # print(reg)
    # reobj = re.compile(reg)
    for f in os.listdir('.'):
        if fnmatch.fnmatch(f, '*d0' + wrf_dom + '*'):
            env["NCL_FIN"] = f
        else:
            env["NCL_FIN"] = None

    return env

def run_ncl(dir):
    global my_env
    os.chdir(dir)
    print("Entered into: " + os.path.abspath("."))
    my_env = set_ncl_fin(my_env)

    if my_env['NCL_FIN'] is None:
        print("No input file is found, Aborting!!")
        sys.exit()

    with open("wo.log.out","w") as out:
        with open("wo.log.err","w") as err:
            print("creating ncl process ...")
            subprocess.Popen("ncl " + wo_path + "/wrfout.ncl", env=my_env,
                             shell=True,universal_newlines=True,
                             stdout=out, stderr=err)

def main():
    try:
        with open(dir_file) as f:
            run_dirs = f.read().split()
    except IOError as e:
        run_dirs=["."]

    for dir in run_dirs:
        run_ncl(dir)

    return

if __name__ == '__main__':
    main()
