#!/usr/bin/env python

import os
import inspect
import sys

# update PYTHONPATH
wo_path = os.path.abspath(os.path.split(inspect.getfile(
    inspect.currentframe()))[0])
if wo_path not in sys.path:
    sys.path.insert(0, wo_path)

if __name__ == '__main__':
    import wrfout
    wrfout.main()
