#!/usr/bin/env python
# [[[cog import cog; cog.out('"""\n{0}\n"""'.format(file('./README.rst').read()))]]]
"""
WRFOUT
======
Common visualizations for WRF model output.

License
-------
GPL v3 (or later)

"""
# [[[end]]]

"""
WO is top level invoke script to run WRFOUT.
"""

AUTHOR = "Yagnesh Raghava Yakkala"
WEBSITE = "http://github.com/yyr/wrfout"
LICENSE ="GPL v3 or later"

import os
import sys
import inspect
import wrfout

wo_path = os.path.abspath(os.path.split(inspect.getfile(
    inspect.currentframe()))[0])

if wo_path not in sys.path:
    sys.path.insert(0, wo_path)

def arg_parse(directories):
    in_file = wrfout.util.find_inputfile()
    print(in_file)

def main(args=None):
    import argparse
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter,
        description=__doc__)
    parser.add_argument('directories',
                        default='.', nargs='*',
                        help='directories in which wrfout is to be run.')

    arg_parse(**vars(parser.parse_args(args)))

if __name__ == '__main__':
    main()
