#!/usr/bin/env bash

export ncl_lib="~/nsc/ncl-lib/"

if [ -f run_dirs ]; then
    run_dirs=`cat ./run_dirs`
    else
    run_dirs=$(pwd)
fi

for dir in $run_dirs; do
    cd $dir
    echo 'entered'

done

ncl $1
